spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: postgres
    password:
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      database: postgresql
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

